# Generated by Django 4.0.1 on 2022-01-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'],
                     'verbose_name': 'Comment',
                     'verbose_name_plural': 'Comments'},
        ),
    ]
